### ISSUE TITLE
Make issues

### ISSUE THREAD

**Issue by KalenAnson** [jessp01/gqlplus#1]
GNU Make 3.81

Getting the following `make` error:

    Makefile:16: *** missing separator.  Stop.

After running `./configure` trying to build this project. Looks like there is a syntax error in the make file. I have been going over it and have yet to get it fixed, so I figured I would report it.

**Comment by jessp01** [comment]
Hi @KalenAnson,

Thanks for reporting. I really don't actively maintain this project any longer as luckily I no longer need to work with Oracle and it's the only reason one would use it:)

That said, your problem can be fixed by running:
```
$ rm configure Makefile
$ autoreconf --install
```
Then continue with:
```
$ ./configure && make
```

GNU's autotools change often and break compatibility very frequently so configure and make files generated with older versions [as the one in the repo is] will often fail to work with newer autotools versions.

**Comment by KalenAnson** [comment]
Thanks, that cleared up the makefile errors. I am now getting a bunch of clang warnings. I may go through and clean some of those up and submit a PR if you are open to it.

Oracle DB is a real chore to use from the terminal, especially with no readline support. This project is a real gem in that respect. Love to help keep it up to date.

**Comment by jessp01** [comment]
Hi @KalenAnson,

Thanks for the kind words:) Yes, it helped me plenty when I had to work with Oracle's DB too.
I actually took ownership of this from  Ljubomir J. Buturovic, see https://github.com/jessp01/gqlplus#authors since he too stopped working on it. I suppose that's the nature of such projects:)

Anyhow, you are certainly welcome to submit pull requests and I'll gladly review them.

**Comment by jessp01** [comment]
Also, added Travis CI config so that every change will trigger a build.
Indeed, there are several warnings worth fixing:
https://travis-ci.org/jessp01/gqlplus/builds/336124131

**Comment by ozcoder** [comment]
Hmm, In my branch I suggested building it like this.

$ aclocal
$ autoconf
$ automake --add-missing
$ ./configure
$ make

Is using autoreconf better?

**Comment by jessp01** [comment]
Hi @ozcoder,

If you'll look at autoreconf's code [it's a Perl script], you'll see it simply runs ```autoconf``` (and ```autoheader```, ```aclocal```, ```automake```, ```autopoint``` and ```libtoolize``` where appropriate).

So, really, it's nothing more than a [very] convenient wrapper:)
